apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # This tells Kubernetes to run 3 identical Pods
  selector:
    matchLabels:
      app: nginx
  template:    # This is the Pod template
    metadata:
      labels:
        app: nginx  # This label connects the Pod to the Deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.25  # The container image to run
          ports:
            - containerPort: 80  # The port the app listens on