# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-microservice.fullname" . }}
  labels:
    {{- include "my-microservice.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.podAnnotations }}
      {{ toYaml . | nindent 4 }}
      {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-microservice.selectorLabels" . | nindent 8 }}
          {{- if .Values.podLabels }}
          {{ toYaml .Values.podLabels | nindent 8 }}
          {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}