# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: deployment-lab
spec:
  selector:
    app: weather-api
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP